### ISSUE TITLE
Start APK using this plugin

### ISSUE THREAD

**Issue by mazito** [petervojtek/cordova-plugin-shell-exec#1]
Can the plugin be used to start an external APK, or it can only run OS commands ?
Thanks for any info.
Mario

**Comment by petervojtek** [comment]
hi Mario,
I have not tried anything else than run OS commands.

**Comment by mazito** [comment]
Hi Peter, thanks for answering ! I supossed it.
Mario

**Comment by maxlinux2000** [comment]
Hi Mazito

Please have a look here:
https://github.com/lampaa/com.lampa.startapp/issues/42

at the end of the page, you can found a working solution for your problem, actualized to the last version of lampaa.startapp plugin.

regards
MaX

**Comment by gardner** [comment]
Did you try using the `pm` command to start the package id?

**Comment by gardner** [comment]
http://stackoverflow.com/questions/4567904/how-to-start-an-application
